// Extend NextAuth typings for this project.
// This file is placed at the repo root so it is picked up by the TypeScript
// config generated by Nuxt (which includes `../*.d.ts`).

// Nuxt adds a virtual `#auth` import that exposes the runtime handler.
// The official package doesn’t export the function directly from its root
// typings, so we declare a lightweight stub here.

declare module "#auth" {
  const NuxtAuthHandler: any;
  export { NuxtAuthHandler };
}

// Extend NextAuth types so our session always includes `user.id` (and tokens).
// This makes `session.user.id` usable in client code without TS errors.

declare module "next-auth" {
  interface Session {
    user: {
      name?: string | null;
      email?: string | null;
      image?: string | null;
      id: string;
      accessToken?: string;
      idToken?: string;
    };
  }
}

declare module "next-auth/jwt" {
  interface JWT {
    accessToken?: string;
    idToken?: string;
  }
}
