name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
      - name: Remove any existing .npmrc
        run: rm -f ~/.npmrc
      - name: Configure npm registry
        run: |
          npm config delete //registry.npmjs.org/:_authToken
          npm config set registry https://registry.npmjs.org/
      - run: npm ci
      - run: npm run test
